/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Platform_Types.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE       0x40021000
#define GPIOA_BASE     0x40010800

#define RCC_APB2ENR    *( vuint32_t*)(RCC_BASE+0x18)
#define GPIOA_CRH      *( vuint32_t*)(GPIOA_BASE+0x04)
#define GPIOA_ODR         *( vuint32_t*)(GPIOA_BASE+0x0c)

int main(void)
{
	vuint16_t i ;
	//set bit2 at APB2ENR to enable the clock
	RCC_APB2ENR|=(1<<2);
	//masking to clear bits from 20 to 23
	GPIOA_CRH &=0xff0fffff;
	//set 2 in bits from 20 to 23
	GPIOA_CRH |=0x00200000;
	while (1)
	{
		//set pin 13
		GPIOA_ODR|=(1<<13);
		//delay
		for(i=0;i<500;i++);
		//clear pin 13
		GPIOA_ODR&=~(1<<13);
		//delay
		for(i=0;i<500;i++);
	}

    /* Loop forever */
	for(;;);
}
